version: '3'
services:
  postgres-database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      TZ: America/Guatemala
    volumes:
      - ./hohorizonte_gt.sql:/docker-entrypoint-initdb.d/horizonte_gt.sql